name: Deploy

on:
  pull_request:
    types:
      - closed
    branches: [ "master" ]
  # push:
  #   branches:
  #     - master


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: Deploy to server
        run: |
          echo "Starting deployment..." 
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'export NVM_DIR="$HOME/.nvm"; [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"; cd /home/${{ secrets.SSH_USER }}/projects/khorn_time && git pull origin master && yarn build && rm -r /var/www/admin/data/www/khorn.pro/* && cp -r /home/${{ secrets.SSH_USER }}/projects/khorn_time/dist/* /var/www/admin/data/www/khorn.pro/ && service nginx reload && systemctl restart nginx'
          echo "Deployment completed."
      - name: cleanup keys
        if: always()
        run: rm -rf ~/.ssh